### ISSUE TITLE
Deep Rank --failed to open the Similarity Editor

### ISSUE THREAD

**Issue by ICC-qi** [paucarre/tiefvision#66]
I think the reason of the following error of failing to open the Similarity Editor web page is my failing to generate the SIMILARITY database.
(When checking my H2 database, I can find correct data stored in the BOUNDING_BOX db, but no data stored in the SIMILARITY db)
So have I forgotten any necessary things to generate the SIMILARITY database in H2?
![2017-11-13 175128](https://user-images.githubusercontent.com/31842521/32719434-5c396882-c89b-11e7-88c8-0156a172219d.png)

---older edition
I have finished all except Supervised Image Similarity (Deep Rank). But when I open the Similarity Editor for the first step, I have got the error in the following picture. Have I forgotten any necessary things?
![2017-11-09 18 18 07](https://user-images.githubusercontent.com/31842521/32600373-6491c1ba-c57a-11e7-9e1e-2530b93c86fb.png)
[error] - application - 

! @760kb02li - Internal server error, for (GET) [/similarity_editor] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalArgumentException: bound must be positive]]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:50) [play-server_2.11-2.4.6.jar:2.4.6]
at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:59) [play-server_2.11-2.4.6.jar:2.4.6]
at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:57) [play-server_2.11-2.4.6.jar:2.4.6]
at scala.util.Either$RightProjection.flatMap(Either.scala:522) [scala-library.jar:na]
at play.core.server.Server$class.getHandlerFor(Server.scala:57) [play-server_2.11-2.4.6.jar:2.4.6]
at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:33) [play-netty-server_2.11-2.4.6.jar:2.4.6]
at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:132) [play-netty-server_2.11-2.4.6.jar:2.4.6]
at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:132) [play-netty-server_2.11-2.4.6.jar:2.4.6]
at scala.util.Either.fold(Either.scala:99) [scala-library.jar:na]
at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:120) [play-netty-server_2.11-2.4.6.jar:2.4.6]
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty.jar:na]
at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [netty-http-pipelining.jar:na]
at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty.jar:na]
at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty.jar:na]
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty.jar:na]
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty.jar:na]
at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty.jar:na]
at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty.jar:na]
at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty.jar:na]
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty.jar:na]
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty.jar:na]
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty.jar:na]
at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty.jar:na]
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty.jar:na]
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty.jar:na]
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty.jar:na]
at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty.jar:na]
at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty.jar:na]
at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty.jar:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.lang.IllegalArgumentException: bound must be positive
at java.util.Random.nextInt(Random.java:388) ~[na:1.8.0_144]
at scala.util.Random.nextInt(Random.scala:66) ~[scala-library.jar:na]
at core.ImageProcessing$.randomSmilarityImage(ImageProcessing.scala:24) ~[na:na]
at controllers.Application.similarityEditor(Application.scala:63) ~[na:na]
at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:542) ~[na:na]
at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:542) ~[na:na]
at play.core.routing.HandlerInvokerFactory$$anon$12$$anon$13.call(HandlerInvoker.scala:89) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.routing.TaggingInvoker.call(HandlerInvoker.scala:32) ~[play_2.11-2.4.6.jar:2.4.6]
at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12.apply(Routes.scala:542) ~[na:na]
at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12.apply(Routes.scala:542) ~[na:na]
at play.core.routing.GeneratedRouter.call(GeneratedRouter.scala:95) ~[play_2.11-2.4.6.jar:2.4.6]
at router.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:541) ~[na:na]
at router.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:471) ~[na:na]
at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223) ~[scala-library.jar:na]
at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219) ~[scala-library.jar:na]
at play.api.routing.Router$class.handlerFor(Router.scala:38) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.routing.GeneratedRouter.handlerFor(GeneratedRouter.scala:86) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.http.DefaultHttpRequestHandler.routeRequest(HttpRequestHandler.scala:170) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.http.JavaCompatibleHttpRequestHandler.routeRequest(HttpRequestHandler.scala:201) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:166) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:165) ~[play_2.11-2.4.6.jar:2.4.6]
at scala.Option.flatMap(Option.scala:171) ~[scala-library.jar:na]
at play.api.GlobalSettings$class.onRouteRequest(GlobalSettings.scala:165) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.DefaultGlobal$.onRouteRequest(GlobalSettings.scala:212) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.GlobalSettings$class.onRequestReceived(GlobalSettings.scala:110) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.DefaultGlobal$.onRequestReceived(GlobalSettings.scala:212) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.http.GlobalSettingsHttpRequestHandler.handlerForRequest(HttpRequestHandler.scala:183) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:38) ~[play-server_2.11-2.4.6.jar:2.4.6]
at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:37) ~[play-server_2.11-2.4.6.jar:2.4.6]
at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library.jar:na]
at scala.util.Try$.apply(Try.scala:191) ~[scala-library.jar:na]
at scala.util.Success.map(Try.scala:236) ~[scala-library.jar:na]
at play.core.server.Server$class.sendHandler$1(Server.scala:37) [play-server_2.11-2.4.6.jar:2.4.6]
at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:58) [play-server_2.11-2.4.6.jar:2.4.6]
	... 38 common frames omitted

**Comment by huafengw** [comment]
That's because the backend tries to load all the images under folder `$TIEFVISION_HOME/src/torch/data/db/similarity/img-enc-cnn` but there is no image there. The Developer Guide doesn't mention what should we do with that folder so I don't know how to solve this one either :(

**Comment by ICC-qi** [comment]
@huafengw I have discarded the part of scala and use the codes in lua files of torch only. Thank you all the same very much for your answer.
